apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: worker
    app: voting-app
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
    spec:
      containers:
      - image: {{.Values.image}}
        name: worker
